/**
 * Committed ONNX seam-probe model access (Phase 7 item #3).
 *
 * `data/fixtures/models/ecg-lab-probe-linear-mean-2.onnx` + its matching
 * `…metadata.json` are *committed deterministic artifacts* that exercise the
 * real ONNX Runtime Web seam (Signal → ModelInput → session → interpret). They
 * live in the committed `data/fixtures/` tree (never gitignored, unlike
 * `data/raw|processed`) and are regenerated byte-identically by
 * `data/fixtures/models/generate-probe-model.py` (Python `onnx`).
 *
 * Layering note (mirrors `src/fixtures/golden.ts`): this module depends on
 * Node's fs/path/crypto and is intentionally *not* part of the browser bundle —
 * it exists so the integration test and any Node-side seam exercise share one
 * source of truth for "what the probe model is". The integrity guard records
 * the committed `.onnx` byte length and SHA-256 so the binary can never drift
 * silently: a stray regeneration that changes the bytes fails loudly instead of
 * quietly altering the oracle.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ModelMetadata } from '../../domain/ml';
import { parseModelMetadataJson } from '../metadata';

/** Directory holding the committed model artifacts. */
export const MODELS_ROOT = join(process.cwd(), 'data', 'fixtures', 'models');

export const PROBE_MODEL_ID = 'ecg-lab-probe-linear-mean-2';
export const PROBE_MODEL_VERSION = '1.0.0';
export const PROBE_MODEL_TASK =
    'probe-sign-of-mean (development seam-validation; not a physiological classifier)';

/** The probe expects a single channel of 360 samples at the lab's 360 Hz. */
export const PROBE_MODEL_SAMPLE_RATE_HZ = 360;
export const PROBE_MODEL_CHANNELS = 1;
export const PROBE_MODEL_WINDOW_SAMPLES = 360;

export const PROBE_MODEL_INPUT_NAME = 'signal';
export const PROBE_MODEL_OUTPUT_NAME = 'logits';
export const PROBE_MODEL_CLASS_LABELS = Object.freeze([
    'positive-mean',
    'nonpositive-mean',
] as const);

/** Integrity record of the committed `.onnx` bytes (from the generator run). */
export const PROBE_MODEL_ONNX_BYTE_LENGTH = 543;
export const PROBE_MODEL_ONNX_SHA256 = 'deec0c5b9d42c243515d7b23160aff91f883c8cfeb5cb9f06d47ffcdd3987052';

export const PROBE_MODEL_ONNX_FILE = join(MODELS_ROOT, `${PROBE_MODEL_ID}.onnx`);
export const PROBE_MODEL_METADATA_FILE = join(MODELS_ROOT, `${PROBE_MODEL_ID}.metadata.json`);

/** Read the committed metadata and return it strictly validated + typed. */
export function loadProbeModelMetadata(): ModelMetadata {
    const text = readFileSync(PROBE_MODEL_METADATA_FILE, { encoding: 'utf8' });
    return parseModelMetadataJson(text);
}

/** Read the committed `.onnx` model bytes (freshly owned). */
export function loadProbeModelBytes(): Uint8Array {
    return new Uint8Array(readFileSync(PROBE_MODEL_ONNX_FILE));
}

/**
 * Verify the committed artifacts against the recorded expectations. Returns an
 * empty list when healthy; otherwise one human-oriented problem per fault. This
 * is the "fixtures cannot drift silently" guard for a binary artifact that has
 * no in-memory TS regenerator (its source is the Python generator script).
 */
export function describeProbeModelProblems(): readonly string[] {
    const problems: string[] = [];

    let bytes: Uint8Array;
    try {
        bytes = loadProbeModelBytes();
    } catch {
        problems.push(`Committed model file is missing: ${PROBE_MODEL_ONNX_FILE}.`);
        return problems;
    }

    if (bytes.byteLength !== PROBE_MODEL_ONNX_BYTE_LENGTH) {
        problems.push(
            `Committed model is ${bytes.byteLength} bytes but the recorded length is ${PROBE_MODEL_ONNX_BYTE_LENGTH}; ` +
            'the artifact changed without a re-baseline.',
        );
    }
    const digest = createHash('sha256').update(bytes).digest('hex');
    if (digest !== PROBE_MODEL_ONNX_SHA256) {
        problems.push(
            `Committed model SHA-256 ${digest} does not match the recorded ${PROBE_MODEL_ONNX_SHA256}; ` +
            'the artifact changed without a re-baseline.',
        );
    }

    try {
        loadProbeModelMetadata();
    } catch (cause) {
        problems.push(
            `Committed metadata failed to parse/validate (${PROBE_MODEL_METADATA_FILE}).`,
        );
        if (cause instanceof Error) {
            problems.push(cause.message);
        }
    }

    return problems;
}
