import { describe, expect, it } from 'vitest';
import { assertValidModelMetadata } from '../../metadata';
import {
    describeProbeModelProblems,
    loadProbeModelBytes,
    loadProbeModelMetadata,
    PROBE_MODEL_CHANNELS,
    PROBE_MODEL_CLASS_LABELS,
    PROBE_MODEL_ID,
    PROBE_MODEL_INPUT_NAME,
    PROBE_MODEL_ONNX_BYTE_LENGTH,
    PROBE_MODEL_OUTPUT_NAME,
    PROBE_MODEL_SAMPLE_RATE_HZ,
    PROBE_MODEL_VERSION,
    PROBE_MODEL_WINDOW_SAMPLES,
} from '../probeModel';

/**
 * Committed ONNX seam-probe artifact regression test (Phase 7 item #3).
 *
 * The `.onnx` is a binary generated by a Python script
 * (`data/fixtures/models/generate-probe-model.py`), so — unlike the JSON golden
 * files in `src/fixtures/golden.ts` — it cannot be regenerated in memory from
 * TypeScript. Its anti-drift guard is the recorded byte length + SHA-256 plus a
 * strict metadata parse; the real *runtime* gate (loading the bytes into an
 * actual ONNX session) is the item #4 integration test in `src/ml/onnx/`.
 */
describe('probe model committed artifact', () => {
    it('loads metadata that passes strict schema validation with the expected envelope', () => {
        const metadata = loadProbeModelMetadata();
        assertValidModelMetadata(metadata);

        expect(metadata.modelId).toBe(PROBE_MODEL_ID);
        expect(metadata.modelVersion).toBe(PROBE_MODEL_VERSION);
        expect(metadata.task.length).toBeGreaterThan(0);

        expect(metadata.input.name).toBe(PROBE_MODEL_INPUT_NAME);
        expect(metadata.input.shape).toEqual([PROBE_MODEL_WINDOW_SAMPLES]);
        expect(metadata.input.dtype).toBe('float32');
        expect(metadata.input.layout.length).toBeGreaterThan(0);

        expect(metadata.expectedSamplingRateHz).toBe(PROBE_MODEL_SAMPLE_RATE_HZ);
        expect(metadata.expectedChannels).toBe(PROBE_MODEL_CHANNELS);
        expect(metadata.expectedWindowSamples).toBe(PROBE_MODEL_WINDOW_SAMPLES);

        expect(metadata.output.name).toBe(PROBE_MODEL_OUTPUT_NAME);
        expect(metadata.output.dtype).toBe('float32');
        expect(metadata.output.semantics).toBe('logits');
        expect(metadata.output.activation).toBe('softmax');
        expect(metadata.output.classLabels).toEqual(PROBE_MODEL_CLASS_LABELS);

        expect(metadata.normalization.strategy).toBe('none');
        expect(metadata.preprocessingAssumptions.length).toBeGreaterThan(0);
        // The probe never claims training data or scientific validity.
        expect(metadata.provenance.trainingDataset?.length ?? 0).toBeGreaterThan(0);
        expect(metadata.provenance.limitations?.length ?? 0).toBeGreaterThan(0);
    });

    it('loads non-empty onnx bytes of the recorded committed length', () => {
        const bytes = loadProbeModelBytes();
        expect(bytes).toBeInstanceOf(Uint8Array);
        expect(bytes.byteLength).toBe(PROBE_MODEL_ONNX_BYTE_LENGTH);
        expect(bytes.byteLength).toBeGreaterThan(0);
    });

    it('reports no integrity problems (byte length, sha-256 and metadata parse)', () => {
        // Guards the binary against silent drift / tampering.
        expect(describeProbeModelProblems()).toEqual([]);
    });
});
